//include: [comment token]?
enum tigerTokens {ARRAY=257,IF,THEN,
				ELSE,WHILE,FOR,TO,
				DO,LET,IN,END,OF,
				BREAK,NIL,FUNCTION,
				VAR,TYPE,IMPORT,PRIMITIVE,
				CLASS,EXTENDS,METHODS,NEW,
				COMMA,COLON,SEMICOLON,
				LPAREN,RPAREN,LBRACKET,RBRACKET,
				LBRACE,RBRACE,DOT,PLUS,MINUS,STAR,
				FSLASH,EQUAL,NOTEQUAL,LESS,GREATER,
				ELESS,EGREATER,AND,OR,
				ASSIGNMENT,ENDL,STRINGLIT,INTLIT,
				IDENTIFIER,ERROR};
